on:
  pull_request:
    types: [labeled, unlabeled]

jobs:
  assign_to_project:
    runs-on: ubuntu-latest
    name: Assign a PR to project based on label
    steps:
      - name: Assign to project
        uses: elastic/github-actions/project-assigner@c73a6dd0666a47e53ba0fc7c2bd2189d76843ed8
        id: project_assigner
        with:
          issue-mappings: |
            [
              {"label": "wf_test", "projectNumber": 1, "columnName": "In progress"}
            ]
          ghToken: ${{ secrets.PROJECT_ASSIGNER_TEST_TOKEN }}

