on:
  pull_request:
    types: [labeled, unlabeled]

jobs:
  assign_to_project:
    runs-on: ubuntu-latest
    name: Assign a PR to project based on label
    steps:
      - name: Assign to project
        uses: elastic/github-actions/project-assigner@829f3782218ec6d8b7fcf2b075f60f220b88d7fc
        id: project_assigner
        with:
          issue-mappings: |
            [
              {"label": "wf_test", "projectNumber": 1, "columnName": "In progress"}
            ]
          ghToken: ${{ secrets.PROJECT_TEST_ASSIGNER_TOKEN }}

