on:
  issues:
    types: [labeled, unlabeled]

jobs:
  assign_to_project:
    runs-on: ubuntu-latest
    name: Assign issue or PR to project based on label
    steps:
      - name: Assign to project
        uses: elastic/github-actions/project-assigner@b57adc9d9a0f46351c878e14b0e4e43d6d18ac9f
        id: project_assigner
        with:
          issue-mappings: '[{"label": "wf_test", "projectNumber": 1, "columnName": "To do"}]'
          ghToken: ${{ secrets.PROJECT_ASSIGNER_TEST_TOKEN }}


